### ISSUE TITLE
Add pull_request trigger to the check.yaml GH Action?

### ISSUE THREAD

**Issue by kinow** [ecmwf/aviso#4]
Hi,

I was waiting for GH Actions to run the tests for #3 , but only the CLA bot ran. I checked `check.yaml`, and looks like it's only triggered manually or after it is merged to `develop`. Is there any reason for not running the CI tests for every pull request?

Thanks
-Bruno

**Comment by jameshawkes** [comment]
Thanks for reporting. Will fix!
